const express = require('express');
const path = require('path');
const { makeWASocket, useMultiFileAuthState, fetchLatestBaileysVersion, DisconnectReason } = require('@whiskeysockets/baileys');
const pino = require('pino');
const config = require('./config');

const app = express();
app.use(express.json());
app.use(express.static('public'));

let sessionStore = new Map();

// Welcome message display
console.log(config.welcomeMessage);

// Main pairing endpoint
app.post('/code', async (req, res) => {
    const { number } = req.body;
    
    if (!number) {
        return res.json({ error: 'نمبر درج کریں' });
    }
    
    try {
        console.log(`\n📱 Pairing request for: ${number}`);
        console.log(`👤 Request by: YOUSAF BALOCH TECH`);
        console.log(`🔗 Channel: ${config.socialMedia.whatsappChannel}`);
        
        const { state, saveCreds } = await useMultiFileAuthState(`./session`);
        const { version } = await fetchLatestBaileysVersion();
        
        const sock = makeWASocket({
            version,
            logger: pino({ level: 'silent' }),
            printQRInTerminal: false,
            auth: state,
            browser: ['YOUSAF-BALOCH-MD', 'Chrome', '1.0.0']
        });
        
        if (!sock.authState.creds.registered) {
            let phoneNumber = number.replace(/[^0-9]/g, '');
            
            if (!phoneNumber.startsWith('92')) {
                phoneNumber = '92' + phoneNumber.replace(/^0/, '');
            }
            
            setTimeout(async () => {
                try {
                    const code = await sock.requestPairingCode(phoneNumber);
                    const formattedCode = code?.match(/.{1,4}/g)?.join('-') || code;
                    
                    console.log(`\n✅ Pairing Code Generated: ${formattedCode}`);
                    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
                    console.log(`📱 WhatsApp: ${config.socialMedia.whatsappChannel}`);
                    console.log(`🎥 YouTube: ${config.socialMedia.youtube}`);
                    console.log(`🎵 TikTok: ${config.socialMedia.tiktok}`);
                    console.log(`📞 Phone: ${config.socialMedia.phone}`);
                    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`);
                    
                    res.json({ 
                        code: formattedCode,
                        message: 'Code generated by YOUSAF BALOCH',
                        social: config.socialMedia
                    });
                } catch (error) {
                    res.json({ error: error.message });
                }
            }, 3000);
        }
        
        sock.ev.on('creds.update', saveCreds);
        
        sock.ev.on('connection.update', async (update) => {
            const { connection, lastDisconnect } = update;
            
            if (connection === 'open') {
                console.log(`\n🎉 Connection Successful!`);
                console.log(`💚 YOUSAF BALOCH MD Connected`);
                console.log(`\n🌟 Follow our social media:`);
                console.log(`📱 ${config.socialMedia.whatsappChannel}`);
                console.log(`🎥 ${config.socialMedia.youtube}`);
                console.log(`🎵 ${config.socialMedia.tiktok}\n`);
            }
            
            if (connection === 'close') {
                const reason = new Boom(lastDisconnect?.error)?.output?.statusCode;
                if (reason !== DisconnectReason.loggedOut) {
                    console.log('Reconnecting...');
                }
            }
        });
        
    } catch (error) {
        console.error('Error:', error);
        res.json({ error: error.message });
    }
});

// Root endpoint
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Start server
const PORT = config.port;
app.listen(PORT, () => {
    console.log(`\n🚀 Server running on port ${PORT}`);
    console.log(`🌐 Open: http://localhost:${PORT}`);
    console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
    console.log(`💻 Created by YOUSAF BALOCH`);
    console.log(`📱 ${config.socialMedia.whatsappChannel}`);
    console.log(`🎥 ${config.socialMedia.youtube}`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`);
});
